import { MotionPlanSchema } from "./types";

export const defaultMotionPlan: MotionPlanSchema = {
  version: "2.0",
  topic: "How Recursion Works in Hardware",
  duration: 15.0,
  fps: 30,
  total_frames: 450,
  creative_direction: {
    style_id: "cyberpunk",
    palette: {
      id: "electric_matrix",
      name: "Electric Matrix",
      background: [10, 14, 23],
      primary: [0, 240, 255],
      secondary: [255, 0, 128],
      accent: [255, 230, 0],
      surface: [18, 24, 38],
      text: [240, 245, 255],
      subtext: [140, 160, 190],
    },
    typography: {
      id: "jetbrains_inter",
      heading: "Inter, sans-serif",
      body: "Inter, sans-serif",
      mono: "JetBrains Mono, monospace",
    },
    hook: {
      headline_template: "CAN YOUR CPU HANDLE RECURSION?",
      subtext_template: "Every frame costs memory. Here is how stack frames live.",
    },
  },
  scenes: [
    {
      id: "scene_1_hook",
      beat_name: "HOOK",
      start: 0.0,
      end: 4.0,
      duration: 4.0,
      visual_type: "hook",
      voice_text: "Wait. Can your CPU really handle unlimited recursion?",
      elements: {
        badge: "HARDWARE DEEP DIVE",
        headline: "CAN YOUR CPU HANDLE RECURSION?",
        subtext: "Every frame costs memory. Here is how stack frames live.",
      },
    },
    {
      id: "scene_2_metaphor",
      beat_name: "MENTAL MODEL",
      start: 4.0,
      end: 8.0,
      duration: 4.0,
      visual_type: "metaphor",
      voice_text: "Think of it physically: call frames pushing onto memory.",
      elements: {
        metaphor_id: "stack_recursion",
        label: "CALL STACK SIMULATION",
        description: "Contiguous stack memory allocated per invocation.",
      },
    },
    {
      id: "scene_3_code",
      beat_name: "CODE EXECUTION",
      start: 8.0,
      end: 11.5,
      duration: 3.5,
      visual_type: "code",
      voice_text: "Here is the exact assembly and memory boundary check.",
      elements: {
        filename: "recurse_stack.py",
        lines: [
          "def recurse(n):",
          "    if n <= 1: return 1",
          "    return n * recurse(n - 1)",
        ],
        highlight_line: 2,
        annotation: "base case halts call frame allocation",
      },
    },
    {
      id: "scene_4_payoff",
      beat_name: "PAYOFF",
      start: 11.5,
      end: 15.0,
      duration: 3.5,
      visual_type: "payoff",
      voice_text: "That is bounded recursion. Deterministic memory safety.",
      elements: {
        title: "DETERMINISTIC MEMORY",
        stat: "O(1) AUX",
        subtitle: "Tail-call optimization transforms frames into loops.",
      },
    },
  ],
  continuity_bridges: [
    {
      from_scene: "scene_1_hook",
      to_scene: "scene_2_metaphor",
      from_type: "hook",
      to_type: "metaphor",
      carry_primitive: "expand",
      carrier_element: "headline_text",
      carrier_description: "Headline pulse transforms outward into the stack boundary container",
      exit_scale: 1.35,
      entry_scale: 0.92,
      overlap_frames: 14,
      motion_blur_intensity: 0.7,
      camera_continuity: "punch_z",
      easing: "expo_out",
      continuity_score_contribution: 92,
      is_slideshow: false,
    },
    {
      from_scene: "scene_2_metaphor",
      to_scene: "scene_3_code",
      from_type: "metaphor",
      to_type: "code",
      carry_primitive: "collapse",
      carrier_element: "stack_frame_node",
      carrier_description: "Top stack frame collapses into the base-case line highlight reticle",
      exit_scale: 1.15,
      entry_scale: 0.88,
      overlap_frames: 14,
      motion_blur_intensity: 0.65,
      camera_continuity: "maintain",
      easing: "cubic_out",
      continuity_score_contribution: 88,
      is_slideshow: false,
    },
    {
      from_scene: "scene_3_code",
      to_scene: "scene_4_payoff",
      from_type: "code",
      to_type: "payoff",
      carry_primitive: "morph",
      carrier_element: "highlight_line",
      carrier_description: "Highlighted return token morphs into the bold payoff O(1) stat badge",
      exit_scale: 1.25,
      entry_scale: 0.95,
      overlap_frames: 16,
      motion_blur_intensity: 0.6,
      camera_continuity: "orbit_continue",
      easing: "expo_out",
      continuity_score_contribution: 94,
      is_slideshow: false,
    },
  ],
  continuity_report: {
    continuity_score: 91.3,
    passed: true,
    slideshow_ratio: 0.0,
    slideshow_bridge_count: 0,
    total_bridges: 3,
    bridge_scores: [
      {
        bridge: {
          from_scene: "scene_1_hook",
          to_scene: "scene_2_metaphor",
          from_type: "hook",
          to_type: "metaphor",
          carry_primitive: "expand",
          carrier_element: "headline_text",
          carrier_description: "Headline pulse transforms outward into the stack boundary container",
          exit_scale: 1.35,
          entry_scale: 0.92,
          overlap_frames: 14,
          motion_blur_intensity: 0.7,
          camera_continuity: "punch_z",
          easing: "expo_out",
          continuity_score_contribution: 92,
          is_slideshow: false,
        },
        score: 92,
        is_slideshow: false,
        passed: true,
      },
      {
        bridge: {
          from_scene: "scene_2_metaphor",
          to_scene: "scene_3_code",
          from_type: "metaphor",
          to_type: "code",
          carry_primitive: "collapse",
          carrier_element: "stack_frame_node",
          carrier_description: "Top stack frame collapses into the base-case line highlight reticle",
          exit_scale: 1.15,
          entry_scale: 0.88,
          overlap_frames: 14,
          motion_blur_intensity: 0.65,
          camera_continuity: "maintain",
          easing: "cubic_out",
          continuity_score_contribution: 88,
          is_slideshow: false,
        },
        score: 88,
        is_slideshow: false,
        passed: true,
      },
      {
        bridge: {
          from_scene: "scene_3_code",
          to_scene: "scene_4_payoff",
          from_type: "code",
          to_type: "payoff",
          carry_primitive: "morph",
          carrier_element: "highlight_line",
          carrier_description: "Highlighted return token morphs into the bold payoff O(1) stat badge",
          exit_scale: 1.25,
          entry_scale: 0.95,
          overlap_frames: 16,
          motion_blur_intensity: 0.6,
          camera_continuity: "orbit_continue",
          easing: "expo_out",
          continuity_score_contribution: 94,
          is_slideshow: false,
        },
        score: 94,
        is_slideshow: false,
        passed: true,
      },
    ],
    violations: [],
    recommendation: "High visual continuity verified across all beats.",
  },
};

